# -*- coding: utf-8 -*-
"""1차정리문제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMq3F4GhjOXAaNUcooHnb-YL5XVKJ2tq
"""

#1. 아이디와 이름을 입력받아 프린트하기

id, name = input('아이디와 이름을 입력하세요(,로 구분해주세요) : ').split(',')
print('아이디가 ' + id + '인 ' + name + '님이 로그인 되었습니다.')

#2. 두 수를 입력받아서 산술연산을 하여 프린트하기

num1 = int(input('첫번째 숫자를 입력하세요 : '))
num2 = int(input('두번째 숫자를 입력하세요 : '))
sum = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = int(num1 / num2)
rim = num1 % num2
print('-----------------------------------------')
print('두 수의 합은 ', sum, '입니다.')
print('두 수의 차은 ', sub, '입니다.')
print('두 수의 곱은 ', mul, '입니다.')
print('두 수의 나눗셈은 ', div, '입니다.')
print('두 수를 나누고 나서의 나머지는 ', rim, '입니다.')
print('-----------------------------------------')

#3 이름과 현재 나이를 입력받아서 프린트하기

name, age = input('이름과 현재 나이를 입력하세요.(,로 구분해주세요) : ').split(',')
age_int = int(age)
age_sum = age_int + 10
print(name, '님의 10년 후의 나이는 ', age_sum, '세입니다.')

#4_1 다음과 같이 판별되도록 프린트(10000원 기준)

money = int(input('엄마 용돈 주세요 : '))
if money >= 10000:
    print('엄마 용돈이 너무 많아요.')
else:
    print('엄마 용돈이 너무 적어요.')

#4_2

money = int(input('엄마 용돈 주세요 : '))
if money >= 10000:
    print('엄마 용돈이 너무 많아요.')
else:
    print('엄마 용돈이 너무 적어요.')

#5_1 숫자를 입력하여 짝/홀을 판별해보세요

num = int(input('원하는 숫자를 입력해주세요(짝/홀판별) : '))
rim = num % 2
if rim == 0:
    print('입력하신 숫자 ', num, '은(는) 짝수입니다.')
else:
    print('입력하신 숫자 ', num, '은(는) 홀수입니다.')

#5_2 숫자를 입력하여 짝/홀을 판별해보세요

num = int(input('원하는 숫자를 입력해주세요(짝/홀판별) : '))
rim = num % 2
if rim == 0:
    print('입력하신 숫자 ', num, '은(는) 짝수입니다.')
else:
    print('입력하신 숫자 ', num, '은(는) 홀수입니다.')

#6 실적목표 달성여부 확인

goal = int(input('실적을 입력하세요>> '))
if goal >= 1000:
    print('-> 축하합니다. 실적을 달성하셧습니다.!')
    bonus = int(goal * 0.2)
    print('-> 당신의 이번달 보너스는 ', bonus, '만원입니다.')
else:
    print('-> 안타깝네요. 다음에는 꼭 달성하세요.!')

#7.

m_name = input('미사일의 이름을 입력하세요. : ')
m_start = float(input('미사일의 시작값을 입력하세요. : '))
m_move = float(input('미사일의 움직이는 값을 입력하세요: '))
m_total = m_start + m_move
print('-------------------------------------------------')
print(m_name, '미사일이 ', m_total,'로 이동되었습니다.')
print('-------------------------------------------------')

#8. 다음 데이터를 입력받아, 영수증을 출력하세요.

cash = int(input('받은 돈 : '))
price = int(input('상품의 총액 : '))
tax = int(price * 0.1)
change = cash - price

print('부가세 : ', tax)
print('잔  돈 : ', change)

#9. 별을 1000개 프린트


for x in range(1, 1001):
    print('*', end = ' ')
    if (x % 25) == 0:
        print()

#10. 1부터20까지 세로로, 가로로 프린트

print('----------------------------')
print('1부터 20까지 세로로 프린트')
for y in range(1, 21):
    print(y)
print('----------------------------')
print()
print('-----------------------------------------------------')
print('1부터 20까지 가로로 프린트')
for x in range(1, 21):
    print(x, end = ' ')
print('-----------------------------------------------------')

#11. 1부터 50까지 중 짝수만 프린트
for x in range(1, 51):
    if (x % 2) == 0:
        print(x, end = ' ')

#12_1. 1부터 1000까지 중 3의 배수의 개수 프린트
count = []
for x in range(1,1001):
    if (x % 3) == 0:
        count.append(x)
print(len(count))

#12_2.
count=0
for x in range(1,1001):
    if (x % 3) == 0:
        count += 1
print(count)

#13
food = []
while True:
    food_name = input('먹고 싶은 음식을 입력하세요.(종료: x):')
    if food_name == 'x':
        print('입력을 종료합니다.')
        print()
        print('--------------------------------------------')
        break
    else:
        food.append(food_name)
print()
print('입력된 음식은', food, '입니다.')

#14 리스트에 먹고 싶은 음식 5개를 넣으세요
#위치값은  index라하고 index는 0부터 시작한다.
food = ['라면', '밥', '고기', '회', '냉면']

print(food)
print(food[0],food[4])
print(food[2])
print(food[2:]) #슬라이싱

#15. 빈 리스트를 만들어서 다음의 값을 하나씩 추가해서 프린트
company = []
company.append('네이버')
company.append('카카오')
company.append('구글')
company.append('링크드인')
print(company)

#16. 리스트를 이용해 다음과 같이 처리되도록 코딩
score = []
for i in range(0,3):
    score_input = int(input('학기 총점 : '))
    score.append(score_input)

sum = 0
for j in range(0,3):
    sum+=score[j]

print('-----------------')
avg = round(sum / len(score))
print('총 학기 평균은' , avg , '점 입니다.')

#17 정답을 맞추는 게임입니다.
goal = 77
count = 0
while True:
    score = int(input('당신이 생각한 정답을 입력하세요 : '))
    count += 1
    if score == 77:
        print('-> 정답입니다.')
        print(count,'번만에 맞추셧습니다. 축하드려요!')
        break
    elif score >= 77:
        print('-> 정답보다 큽니다.')
    else:
        print('-> 정답보다 작습니다.')

# 18 은행 시스템입니다.

print('은행 시스템입니다.')
deposit = float(input('입금액 : '))
interest = float(input('연 이자율 : '))
interest_price = deposit * interest
total = int(deposit + interest_price)
print('---------------------')
print('1년 후 받게 될 금액은 : ', total,'원 입니다.')

#19 나에 대한 5가지 정보를 딕셔너리에 넣어 전체 프린트
my_info = {'이름':'이대준', '나이':31, '성별':'남자', '사는곳':'서울어딘가', '이동수단':'지하철'}
key = input('이름,나이,성별,사는곳,이동수단 중 원하는 것을 입력하세요 : ')
print(key,'은(는)', my_info[key],'입니다.')

#20 내가 가장 좋아하는 장소를 순서대로 입력
place = []
for x in range(0,5):
    data = input('장소를 입력하세요:')
    place.append(data)
print('------------------------------')
print(place)
print('------------------------------')
print('강남이 싫어져서 제거하겠습니다.')
place.remove('강남')
print(place)
print('------------------------------')
print('제주도가 제주시로 바뀌었습니다.')
place[3] = '제주시'
print(place)
print('------------------------------')
y=0
for x in range(0,4):
    y+=1
    print(y,'위 ',place[x])

